services:
  backend:
    image: carloshernan2050/calculadora_backend:v2
    container_name: calculadora_backend
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: calculadora
    depends_on:
      - db
    networks:
      - app_net

  frontend:
    build:
      context: ./frontend
    image: calculadora-docker-db-frontend:latest
    container_name: calculadora_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app_net

  db:
    image: mysql:8.0
    container_name: calculadora_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: calculadora
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_net

volumes:
  db_data:

networks:
  app_net:
    driver: bridge
